name: Release email on release published

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      pr_title:
        required: true
      pr_body:
        required: true
      recipient_email:
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Send PR email
        run: node .github/scripts/sendPrEmail.js
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SENDER_EMAIL: ${{ secrets.AZURE_SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ vars.OUTLOOK_TARGET_EMAIL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
