name: Release email on release published

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_title:
        required: true
      release_body:
        required: true
      recipient_email:
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Send PR email
        run: node .github/scripts/sendReleaseEmail.js
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SENDER_EMAIL: ${{ secrets.AZURE_SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ inputs.recipient_email || vars.OUTLOOK_TARGET_EMAIL }}
          RELEASE_TITLE: ${{ github.event.release.title || inputs.release_title }}
          RELEASE_BODY: ${{ github.event.release.body || inputs.release_body }}
